### PR TITLE
Pull latest Microsemi commits for driver aacraid

### PR DESCRIPTION
**Pull request by dougmill-ibm**
These are the latest changes to the aacraid driver. These have been cherry-picked from linux-next.

---

This change is [Reviewable](https://reviewable.io/reviews/open-power/linux/6)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Shouldn't these go to the linux stable tree? I'd prefer we pick them up from there.

**Comment by shenki** [comment]
How does this differ from https://github.com/open-power/linux/pull/5?

Can you please address the questions from that PR.

**Comment by dougmill-ibm** [comment]
The main reason these commits are important is that they contain bug fixes which can affect petitboot, and some were actually observed in petitboot. The goal was to get these fixes into customer hands as soon as possible.

As far as CC'ing stable, I'd need to understand how linux-next differs and under what circumstances linux-next is not destined for stable. And if the patches needed special handling in order to avoid remaining abandoned on linux-next forever, both I and the vendor need to understand what is required. 

Again, the primary goal is to get fixes to customers as soon as possible. What process will best achieve that?

**Comment by dougmill-ibm** [comment]
There are also additional, important, commits in this PR that were accepted on linux-scsi since.

**Comment by shenki** [comment]
When these patches are authored and sent to the linux-scsi mailing list, the developers need to identify which patches are bug fixes and follow the process documented here:

 https://www.kernel.org/doc/Documentation/stable_kernel_rules.txt

This is the best way to operate in the future as then the patches will appear in the stable tree. The stable tree is what the OpenPower firmware uses, so we get them included "for free".

> Procedure for submitting patches to the -stable tree:
> 
>  - If the patch covers files in net/ or drivers/net please follow netdev stable
>    submission guidelines as described in
>    Documentation/networking/netdev-FAQ.txt
>  - Security patches should not be handled (solely) by the -stable review
>    process but should follow the procedures in Documentation/SecurityBugs.
> 
> For all other submissions, choose one of the following procedures:
> 
>    --- Option 1 ---
> 
>    To have the patch automatically included in the stable tree, add the tag
>      Cc: stable@vger.kernel.org
>    in the sign-off area. Once the patch is merged it will be applied to
>    the stable tree without anything else needing to be done by the author
>    or subsystem maintainer.
> 
>    --- Option 2 ---
> 
>    After the patch has been merged to Linus' tree, send an email to
>    stable@vger.kernel.org containing the subject of the patch, the commit ID,
>    why you think it should be applied, and what kernel version you wish it to
>    be applied to.
> 
>    --- Option 3 ---
> 
>    Send the patch, after verifying that it follows the above rules, to
>    stable@vger.kernel.org.  You must note the upstream commit ID in the
>    changelog of your submission, as well as the kernel version you wish
>    it to be applied to.
> 
> Option 1 is *strongly* preferred, is the easiest and most common.

**Comment by dougmill-ibm** [comment]
Upon review of the linux-scsi mail, some of the commits did include a CC: stable. Oddly, the commit which updated the driver version was NOT cc'ed to stable and so there is no user-visible indicator that the driver was update. Not sure how serious this is, and since not all commits were sent to stable it is not technically correct to label the driver with the new version, although it is also not correct to leave it at the old version.

Any recommendation on how to handle the fact the we have updated the driver but not changed it's version string?

**Comment by shenki** [comment]
Generally, Linux isn't huge on version strings in drivers. Probably for reasons like we're encountering now - they don't provide any real guarantee of functionality.

Speculating, perhaps it wasn't cc'd to stable is that stable don't like to apply trivial patches.

Do we know who depends on this driver version being present and correct?

**Comment by dougmill-ibm** [comment]
It's a general serviceability issue. If we are dealing with a "customer" problem and can't be sure what version of the driver they have, it just makes our job that much more difficult. If there is nothing embedded in the kernel module that can be used to determine it's content, it creates more work and uncertainty. Perhaps the driver level can be inferred most times from the release version, but we then have to ignore the information provided by the vendor/customer about the driver.

**Comment by dougmill-ibm** [comment]
Looking at the previous batch of aacraid patches, it appears all of them were pulled in to linux-stable (including the driver version change). Unsure if the linux-scsi mail included "cc: stable" for all of them or not.

**Comment by stewart-ibm** [comment]
It seems that everything applicable has come in via stable, so closing this issue.

**Pull request closed without merging**
